name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  owner:  # id of input
    description: ''
    required: true
    default: ''
  repo:  # id of input
    description: ''
    required: true
    default: ''
  token:  # id of input
    description: ''
    required: true
    default: ''
  path:  # id of input
    description: ''
    required: true
    default: ''
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
