name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm i
    - name: test
      uses: jihuayu/issues2md@v1
      with:
        owner: jihuayu
        repo: issues2md
        path: .
        token: ${{ secrets.push }}
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        GITHUB_TOKEN: ${{ secrets.push }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: .
  # test action works running from the graph  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        milliseconds: 1000
